name: Bug Report
description: Report a reproducible bug
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
      placeholder: Clear, concise description.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and artifacts
      description: Paste relevant logs or screenshots.
      render: shell
    validations:
      required: false
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Python version, Docker version, and key env vars (redact secrets).
    validations:
      required: false
